name: smart_receipt
description: SmartReceipt — Personal Receipt Scanner & Expense Assistant (skeleton)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  go_router: ^16.1.0
  easy_localization: ^3.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  in_app_purchase: ^3.2.3
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  encrypt: ^5.0.1
  camera: ^0.10.5+9  
  google_mlkit_document_scanner: ^0.2.0      # Camera preview & capture
  google_mlkit_text_recognition: ^0.11.0  # ML Kit OCR
  path_provider: ^2.1.2    # To save images temporarily
  image_picker: ^1.1.2     # Pick images from gallery/camera
  image: ^4.1.7            # Image processing for edge detection and preprocessing

 
  flutter_local_notifications: ^19.4.0
  fl_chart: ^1.0.0
  pdf: ^3.10.1
  csv: ^6.0.0
  google_sign_in: ^7.1.1
  cloud_firestore: ^6.0.0
  intl: ^0.20.2
  device_info_plus: ^9.1.2
  share_plus: ^7.2.1
  url_launcher: ^6.2.4
  
  

#dev_dependencies:
#  flutter_localizations:
#    sdk: flutter
#  flutter_test:
#    sdk: flutter
#  integration_test:
#    sdk: flutter
#  lint: ^2.0.1
#  mockito: ^5.4.0
dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/test_receipts/sample1.jpg
    #- assets/images/
#flutter pub add firebase_core firebase_auth google_sign_in