// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMM7VafouuKV_ZZvhpTNonJSNqbrLf7lo',
    appId: '1:950146446484:web:6f535bca84f82c9df17081',
    messagingSenderId: '950146446484',
    projectId: 'smartreceiptbig',
    authDomain: 'smartreceiptbig.firebaseapp.com',
    storageBucket: 'smartreceiptbig.firebasestorage.app',
    measurementId: 'G-4WX85795K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp07WE1ZyHY6q4yUAEYa-wBTekwnxFNnQ',
    appId: '1:950146446484:android:572a2c10dff4f07cf17081',
    messagingSenderId: '950146446484',
    projectId: 'smartreceiptbig',
    storageBucket: 'smartreceiptbig.firebasestorage.app',
  );

}